### ISSUE TITLE
Docs

### ISSUE THREAD

**Issue by gampleman** [jvandemo/generator-angularjs-library#13]
I think a library should include documentation. It would be good if the defaults included a documentation generator and a watch task for compiling the docs. Also a task to put the docs into the gh-pages branch would be useful.

**Comment by theborakompanioni** [comment]
I am also very interested in this feature. I think [jsdoc](https://github.com/jsdoc3/jsdoc) with [gulp-jsdoc](https://github.com/jsBoot/gulp-jsdoc) would be a suitable solution. Do you agree or do you have other things in mind?

At the time of writing jsdoc is in version 3.3.0.beta1 (after 13 alphas) so it may be a good idea to defer this feature till the next stable release.

**Comment by jvandemo** [comment]
@theborakompanioni Agree, it would be a great feature to have! Are you interested in having a look at it? Love your work so far so would be great to have you working on this.

I don't think there's something wrong with already adding it. As long as it doesn't hamper the build process, it should be fine.

What do you think?

**Comment by theborakompanioni** [comment]
Yes, I am interested in writing this feature. I don't know when I am able to work on it yet.
Since there is a lot of personal style involving the documentation process I'll come back here and report any findings or questions regarding you preferences.

I have worked with jsdoc before but I am definitely not an expert so reviewing the code I'll produce would be very much appreciated.

**Comment by jvandemo** [comment]
Awesome, thanks @theborakompanioni. It's great to having you work on this.

Looking forward to what you come up with. The entire community benefits from great documentation, so it's definitely worth looking into it carefully.

I suggest we start a new PR so we can discuss there.

How does that sound? Thanks again!

**Comment by jvandemo** [comment]
It may be worth looking at https://github.com/angular/dgeni, the tool that is used by AngularJS team to gerenate documentation for Angular 2.0.

**Comment by jvandemo** [comment]
@theborakompanioni &mdash; Have you been able to get into this yet? If not, just let me know and I'll close this issue until picked up again later. Thanks!

**Comment by theborakompanioni** [comment]
@jvandemo I have it in the back of mind but I am just too busy and will not have time in the foreseeable future. Sorry.. I'm rather annoyed about it :/

**Comment by jvandemo** [comment]
@theborakompanioni &mdash; no problem friend, totally understand. Take your time. I will close the issue for now and feel free to have a look at it when you can. Much appreciated!
