### ISSUE TITLE
Could you add documentation on the files generated

### ISSUE THREAD

**Issue by ceoaliongroo** [jvandemo/generator-angularjs-library#2]
Hi, 

Great work with your repo, i like the idea to use yours instead others because the organization of the code. But it's kind of confusing 

Could you explain with you copy this file in the generator?

|     |---- yourLibraryName.prefix
|     |---- yourLibraryName.suffix

Thanks

**Comment by jvandemo** [comment]
@rony76, the wrapper files will no longer be necessary in future releases so I wouldn't recommend using them.

The new AngularJS styleguide makes them obsolete so they will disappear in the next major release.
