### ISSUE TITLE
pre-load HTML templates into $templateCache

### ISSUE THREAD

**Issue by theborakompanioni** [jvandemo/generator-angularjs-library#24]
As enough angularjs modules have directives with html templates it might be a good idea to use [gulp-ng-html2js](https://github.com/marklagendijk/gulp-ng-html2js). Some may not want to include it as the output file will grow in size quite a bit if you have many and/or long html templates - so I'd suggest asking whether or not to include it during setup. Any thoughts?

**Comment by jvandemo** [comment]
Hi @theborakompanioni, I think generator-angularjs-library is more targeted at libraries that don't contain templates instead. Or do you have more specific use cases? Thanks for your feedback!

**Comment by theborakompanioni** [comment]
@jvandemo Just know that I am fine with whatever you want your generator to be (of course!) - but I think this feature would enhance the generator at nearly no cost.
I have a specific use case here [angular-keenio](https://github.com/theborakompanioni/angular-keenio) ([demo](https://theborakompanioni.github.io/angular-keenio)).
See for example the directive: https://github.com/theborakompanioni/angular-keenio/blob/master/src/angular-keenio/directives/keenAreachart.js

It is a small library and therefor the templates can be inlined without major drawbacks - but all in all it would be nice to know that it is possible. But keep in mind: As soon as I really need the feature I would implement it myself - just hoping you will accept a pull request.

Have a nice day.

**Comment by jvandemo** [comment]
@theborakompanioni &mdash; Get it, would love to see this in action. If you can get it working, I would definitely try it out and consider merging if it works well. Thanks!!

**Comment by deyceg** [comment]
+1 

I use this generator alot and the first thing I do every time is setup template-cache :)

**Comment by jvandemo** [comment]
@deyceg & @theborakompanioni &mdash; Would you mind sharing the template caching related config from your gulpfiles so I can see how you both approach it? Thanks!

**Comment by theborakompanioni** [comment]
Sorry for still not having implemented it.. :/ But here is my small example setup:
- gulpfile (task "partials" and "html"): https://github.com/theborakompanioni/vishy-ui/blob/master/gulp/build.js#L27-L70
- package.json: https://github.com/theborakompanioni/vishy-ui/blob/master/package.json#L28 (uses 1.8 instead of 0.2.0)

Hope it is useful. Have a nice day.

**Comment by deyceg** [comment]
```
//Compile templates to tmp folder
gulp.task('templates', function () {
  return gulp.src('src/**/*.html')
    .pipe(templateCache({
      filename: 'my-module-templates.js',
      module: 'myModule.templates'
    }))
    .pipe(gulp.dest('.tmp'));
});

//Add template module to source files
sourceFiles = [
      ...
      '.tmp/templates.js',
      ...
    ];

//Task dependency on build
gulp.task('build', ['templates'], function() {
    ...
})
```

**Comment by jvandemo** [comment]
Thanks @theborakompanioni and @deyceg!

The use cases seem to be varying depending on the individual library requirements.

I am considering adding documentation on how to implement template caching, rather than adding it in the build process by default because the scenario's are too project specific:

- library 1 may only opt to cache a subset of templates
- library 2 may opt to cache all templates
- library 3 may opt to cache nothing at all
- etc...

What are your thoughts?

Thanks!!

**Comment by theborakompanioni** [comment]
that is true indeed. what about asking a simple "enable template caching?" during setup where one can "opt in" for "caching all templates"? personally, i use your generator for projects of rather small size and would even prefer if one would "opt out" of caching - but then, others use it for their specific needs.. anyway - it'd be great if it setups caching automatically.

**Comment by jvandemo** [comment]
Will consider this if there is a rewrite in the future. Meanwhile I will refer similar questions to this thread. Thanks for sharing your learnings @theborakompanioni!
