### ISSUE TITLE
What do tests look like in this framework?

### ISSUE THREAD

**Issue by LOZORD** [jvandemo/generator-angularjs-library#29]
It might be nice to provide an example test. I understand Mocha, Chai, Sinon, etc. However, how would one go about testing services using this framework?

**Comment by LOZORD** [comment]
Just to be clear, `myLibSpec.js` is nice to have, but it doesn't really show how services, etc. are tested in the framework. I've spent a lot of time on SO looking at scary `inject` and `angular.mock.module` code, and I don't know what methodology is correct to use under this framework.

**Comment by jvandemo** [comment]
@LOZORD &mdash; Thanks for the PR, has been merged!
