### ISSUE TITLE
used gulp-angular-embed-templates for packaging Directives with partials

### ISSUE THREAD

**Issue by erikyuzwa** [jvandemo/generator-angularjs-library#31]
Just wanted to thank you for putting this generator together. Really well done, and put me on a great start for my component project.

I struggled quite a while with trying to unit test Directives that pulled in their partial via the `templateUrl` attribute. 

Eventually I came across `gulp-angular-embed-templates` which minimizes and stringifies your partials and embeds them right into your Directives; makes it both far easier to unit test with Karma, and package for use by other projects.

**Comment by jvandemo** [comment]
@erikyuzwa &mdash; I'm sorry, I missed your comment.

Sounds like a great way to make the process easier indeed! Thanks for sharing your learnings. Hopefully others can benefit from them as well.

Would you like to add something to this issue or can I close it as it is?

Thanks again!

**Comment by erikyuzwa** [comment]
yup - I intend to put a blog post together - maybe add it to the end of this issue for others to find (if that's okay with you). Thanks so much!

**Comment by jvandemo** [comment]
@erikyuzwa &mdash; Super, thank you!
