### ISSUE TITLE
how to reference other javascript libraries

### ISSUE THREAD

**Issue by erikyuzwa** [jvandemo/generator-angularjs-library#32]
I'm using the generator to put together a small component library of Directives. It's great so far, but I'd like to now include other libraries like `lodash`.

Since this project has no real `index.html`, where would I put the `lodash` reference. I'm guessing somewhere in the `module.js` file where the Angular references are put together?

**Comment by DenisOS** [comment]
Hi, did you get an answer to this question? 
I'd like to do same. Here's what I've done so far:
I installed a library I needed using bower which updated my bower.json to include the library as a dependency. 
I updated karma-src.conf.js to include the local path to the library in the files property. So my unit tests pass.

**Comment by erikyuzwa** [comment]
No I never did @DenisOS - but at the same time, it's given me time to think about it more and realize that perhaps this is why most libraries leave out those decisions in favour of letting the end-developer integrate my components with any existing codebase which has already likely decided upon issues like underscore vs. lodash vs. library_x.

Like you, I ended up following the same strategy in order to at least be able to unit test.

**Comment by jvandemo** [comment]
The guidelines by @DenisOS look really solid.

What I usually do as well is wrap the native dependency in a service and throw an error if the dependency is not available. Suppose that you require the D3 library:

```javascript
(function () {
  function D3Factory($window) {
    if(!$window.d3){
      throw new Error('D3 is required!');
    }
    return $window.d3;
  }
  D3Factory.$inject = ['$window'];
  angular
    .module('app')
    .factory('d3', D3Factory);
})();
```

the you can inject `d3` anywhere in your application without having to use `window.d3` or `$window.d3`.

This is really convenient. If the developer forgets to include the dependencies, the application wil throw an error and the console will show the reason why.

**Comment by jvandemo** [comment]
@erikyuzwa, @DenisOS: did my example code answer your question(s)?

Thanks!

**Comment by erikyuzwa** [comment]
Yup, I like it! great suggestion indeed. I'll close it, but if @DenisOS needs more help, please don't hesitate to re-open. #high5

**Comment by jvandemo** [comment]
@erikyuzwa &mdash; :+1:

**Comment by DenisOS** [comment]
@jvandemo looks good to me too; thats a nice technique and throwing the exception will help developers know what to fix.

**Comment by jvandemo** [comment]
@DenisOS &mdash; Perfect, thanks for the confirmation!
