### ISSUE TITLE
Add support for es6

### ISSUE THREAD

**Issue by denisos** [jvandemo/generator-angularjs-library#34]
Hi Jurgen, what do you think about adding optional support for ES6?
Devs would have an option to develop in es5 or es6 (which would be built to es5 for distribution).

For example including gulp-babel: https://www.npmjs.com/package/gulp-babel to convert to es5.

Some work would be needed on the linter jshint. I read a little and it now supports es6. e.g.
esversion: 6 But its not clear what exactly from es6 is and is not supported.
I see the current version of the linter is "jshint-stylish": "^0.4.0" in the library. The latest stable npm is v2.8.0 which has es6 support. They been improving es6 support last number of releases https://github.com/jshint/jshint/releases. They have some open ES6 issues but don't seem so bad: https://github.com/jshint/jshint/labels/ES6. Seems like it would be something worth evaluating.

Would also need to consider generating source maps and support those for debugging es6.

**Comment by jvandemo** [comment]
@Denis &mdash; I would really like that.

Do you think it could be integrating without affecting ES5 users?

I assume it would also impact the `test-src` task or how would you see it?

Thanks Denis!

**Comment by DenisOS** [comment]
Hi Jurgen, apologies for delay in replying. Here's what I'm thinking: 
* add a question if user wants to develop in ES5 or ES6. 
* If ES5 then continue as now, no change 
* If ES6 then add a step to the gulpfile to build code from es6 to es5. I think this would impact the `build` step, watch and the linter I expect. Not sure about test-src. I'd have to play around with it.
How does that sound?
What es6 to es5 compiler should be used? babel.js? 


A related question: what about adding a question and step for a css pre-processor? 
I built an angular library recently which has css styles. So I added a gulpfile step for saas. This could also be added as a question and made part of the grunt build if user wants it during configuration.

**Comment by jvandemo** [comment]
@denisos &mdash; I'm going to have a look at including `gulp-babel` by default without asking an extra question.

Running Babel when using ES5 should not impact the code so I don't think there is much value in prompting the user for a unnecessary choice.

What do you think? Thanks!

**Comment by jvandemo** [comment]
There haven't been any other requests for this so I'm going to leave it as is for now.

If anyone else feels this should be brought up again, feel free to add a comment.

Thanks for your input @denisos!

**Comment by kreck** [comment]
Hi Jurgen, i just stumbled upon this issue. I love this generator and I'd love to see ES6 support with Babel! I fear however, that i could not contribute much to implement it...

**Comment by jvandemo** [comment]
Okay &mdash; if someone is willing to implement this, I'm definitely willing to accept a PR for this.
