### ISSUE TITLE
Adding directive templates

### ISSUE THREAD

**Issue by ErikAugust** [jvandemo/generator-angularjs-library#37]
Is there a recommended directory for adding directive HTML templates? Thank you!

**Comment by jvandemo** [comment]
@ErikAugust &mdash; Great question!

The 2 most common ways would be to:

1. Inline the templates in your directives using the `template` property (see [AngularJS docs](https://docs.angularjs.org/guide/directive) for exact syntax).
2. If inlining is not an option, you can put your templates in a directory outside of the `src` directory and use a plugin like [gulp-html2js](https://www.npmjs.com/package/gulp-html2js) to generate Angular code that primes the Angular template cache with your template. [UI-Bootstrap](https://github.com/angular-ui/bootstrap) uses this approach.

Does that answer your question? Thanks!

**Comment by ErikAugust** [comment]
@jvandemo - Makes sense, thanks for the help!

**Comment by jvandemo** [comment]
@ErikAugust &mdash; Welcome Erik, let us know how it went. Thanks!
